Repository eProsima/Fast-CDR, pull requests merged in 2024-09, with the labels that each got.

#227 [21286] Remove CodeQL cron and other branch triggers
  .github/workflows/codeql-analysis.yml
Labels: ready-to-merge, skip-ci

#233 [21556] Bugfix: clear map before deserializing with string as values in XCRv1
  include/fastcdr/Cdr.h
  test/cdr/SimpleTest.cpp
Labels: ci-pending

#235 [21622] Bump version to v2.2.4
  CMakeLists.txt
  package.xml
Labels: skip-ci
