Repository eProsima/Fast-CDR, pull requests merged in 2024-11, with the labels that each got.

#244 [22041] Support setting and encoding options with least significant bits set with possible padding
  include/fastcdr/Cdr.h
  src/cpp/Cdr.cpp
  test/xcdr/appendable.cpp
  test/xcdr/basic_types.cpp
  test/xcdr/external.cpp
  test/xcdr/final.cpp
  test/xcdr/mutable.cpp
  test/xcdr/optional.cpp
  test/xcdr/xcdrv1.cpp
  test/xcdr/xcdrv2.cpp
Labels: ci-pending

#245 [21362] Fail when trying to serialize `std::string` with null characters on its content
  include/fastcdr/Cdr.h
  include/fastcdr/FastCdr.h
  test/cdr/SimpleTest.cpp
Labels: ci-pending, needs-review

#210 Fix: function definition is marked dllimport
  include/fastcdr/Cdr.h
  src/cpp/Cdr.cpp
Labels: ci-pending

#249 [22329] Serialize single null-character for empty strings
  include/fastcdr/Cdr.h
  include/fastcdr/FastCdr.h
  test/cdr/SimpleTest.cpp
Labels: ci-pending

#234 [21619] Fix C2512 compile error with Visual Studio 2015
  include/fastcdr/xcdr/detail/optional.hpp
Labels: ci-pending

#251 [22341] Fix `cmake` generator evaluation
  src/cpp/CMakeLists.txt
Labels: ready-to-merge
