Repository eProsima/Fast-CDR, pull requests merged in 2024-07, with the labels that each got.

#203 [20414] Add PR template
  .github/pull_request_template.md
Labels: ready-to-merge

#216 [21286] Improve CI workflows in master
  .github/pull_request_template.md
  .github/workflows/config/build.meta
  .github/workflows/config/test.meta
  .github/workflows/config/test.repos
  .github/workflows/fastcdr-test.yml
  .github/workflows/mac-ci.yml
  .github/workflows/nightly-mac-ci.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/reusable-ci.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/windows-ci.yml
  README.md
  RELEASE_SUPPORT.md
Labels: ci-pending

#224 [21310] Set 2.1.x (Fast DDS 2.13.x) as EOL
  .github/pull_request_template.md
  .github/workflows/codeql-analysis.yml
  RELEASE_SUPPORT.md
Labels: skip-ci

#228 [21387] Fix windows CI: Avoid usage of removed action
  .github/workflows/reusable-ci.yml
Labels: ready-to-merge

#231 [21365] Bump version to 2.2.3
  CMakeLists.txt
  package.xml
Labels: ci-pending
